apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xrengine
bases:
  - ../../base
patches:
  - production.yaml
secretGenerator:
  - name: xrengine-prod-config
    files:
      - production.json
generatorOptions:
  disableNameSuffixHash: true