# values for nginx-ingress on EKS using Classic ALP

rbac:
  create: true

controller:
  config:
    use-forwarded-headers: "true" # Redirect Insecure traffic to Https
  service:
    targetPorts:
      http: http
      https: http # SSL termination at the load balancer
    annotations:
      meta.helm.sh/release-name: nginx
      meta.helm.sh/release-namespace: default
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-type: "alb"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<ACM Certificate ARN for SSL>"

