{{- if and .Values.director.enabled .Values.director.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xrengine.director.serviceAccountName" . }}
  namespace: {{ include "xrengine.matchmaking-namespace" . }}
  labels:
    {{- include "xrengine.director.labels" . | nindent 4 }}
  {{- with .Values.director.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
