{{- if .Values.matchfunction.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xrengine.matchfunction.fullname" . }}
  namespace: {{ include "xrengine.matchmaking-namespace" . }}
  labels:
    {{- include "xrengine.matchfunction.labels" . | nindent 4 }}
spec:
  type: {{ .Values.matchfunction.service.type }}
  ports:
    - port: {{ .Values.matchfunction.service.port }}
      targetPort: {{ .Values.matchfunction.service.port }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "xrengine.matchfunction.selectorLabels" . | nindent 4 }}
{{- end -}}
