{{- if .Values.matchfunction.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "xrengine.matchfunction.fullname" . }}
  namespace: {{ include "xrengine.matchmaking-namespace" . }}
  labels:
    {{- include "xrengine.matchfunction.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
    verbs:
      - get
      - list
      - watch
{{- end }}
