{{- if and .Values.matchfunction.enabled .Values.matchfunction.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xrengine.matchfunction.serviceAccountName" . }}
  namespace: {{ include "xrengine.matchmaking-namespace" . }}
  labels:
    {{- include "xrengine.matchfunction.labels" . | nindent 4 }}
  {{- with .Values.matchfunction.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
