{{- if .Values.builder.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "xrengine.builder.fullname" . }}
  labels:
    {{- include "xrengine.builder.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - "agones.dev"
    resources:
      - fleets
      - fleet
      - fleets.agones.dev
      - gameservers
      - gameserver
      - gameservers.agones.dev
      - gameserversets
    verbs:
      - get
      - list
      - watch
{{- end }}
