{{- if .Values.builder.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xrengine.builder.fullname" . }}
  labels:
    {{- include "xrengine.builder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.builder.service.type }}
  ports:
    - port: {{ .Values.builder.service.port }}
      targetPort: {{ .Values.builder.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "xrengine.builder.selectorLabels" . | nindent 4 }}
{{- end -}}
