{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xrengine.api.fullname" . }}
  labels:
    {{- include "xrengine.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "xrengine.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xrengine.api.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api-server-configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xrengine.api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      {{- $releaseName := .Release.Name }}
      {{ if not (empty .Values.release) }}
      {{- $releaseName = .Values.release.name | default .Release.Name }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "xrengine.api.fullname" . }}
                optional: true
          env:
            - name: SERVER_MODE
              value: "api"
            - name: KUBERNETES
              value: "true"
            - name: MYSQL_USER
              value: {{ .Values.mariadb.db.user }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.db.name }}
            - name: MYSQL_PASSWORD
              {{- if not .Values.mariadb.enabled }}
              value: {{ .Values.mariadb.db.password | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.existingSecret }}
                  name: {{ .Values.mariadb.existingSecret }}
                  {{- else }}
                  name: {{ template "xrengine.mariadb.fullname" . }}
                  {{- end }}
                  key: mariadb-password
              {{- end }}
            - name: MYSQL_HOST
              value: {{ template "xrengine.mariadb.host" . }}
            - name: MYSQL_PORT
              value: {{ .Values.mariadb.externalPort | quote }}
            - name: REDIS_ENABLED
              value: "true"
            - name: REDIS_ADDRESS
              value: "$({{ $releaseName | upper }}_REDIS_MASTER_SERVICE_HOST)"
            - name: REDIS_PORT
              value: "$({{ $releaseName | upper }}_REDIS_MASTER_SERVICE_PORT)"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $releaseName }}-redis
                  key: redis-password
            - name: RELEASE_NAME
              value: {{ $releaseName }}
          ports:
            - name: http
              containerPort: 3030
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      initContainers:
        - name: init-redis
          image: busybox:1.28
          command: [ 'sh', '-c', 'until (printf "AUTH $REDIS_PASSWORD\r\nPING\r\n";) | nc $REDIS_ADDRESS $REDIS_PORT ; do echo waiting for redis-master; sleep 2; done' ]
          env:
            - name: REDIS_ADDRESS
              value: "$({{ $releaseName | upper }}_REDIS_MASTER_SERVICE_HOST)"
            - name: REDIS_PORT
              value: "$({{ $releaseName | upper }}_REDIS_MASTER_SERVICE_PORT)"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $releaseName }}-redis
                  key: redis-password
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
