{{- if and .Values.editor.enabled .Values.editor.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xrengine.editor.serviceAccountName" . }}
  labels:
    {{- include "xrengine.editor.labels" . | nindent 4 }}
  {{- with .Values.editor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
