{{- if and .Values.gameserver.enabled (ne (.Values.gameserver.ingress.disabled | default "") "true") -}}
{{- $fullName := include "xrengine.gameserver.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "xrengine.gameserver.labels" . | nindent 4 }}
  {{- with .Values.gameserver.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.gameserver.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 3031
{{- end }}