{{- if .Values.testbot.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "xrengine.testbot.fullname" . }}
  labels:
    {{- include "xrengine.testbot.labels" . | nindent 4 }}
spec:
  suspend: {{ .Values.testbot.suspend }}
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "xrengine.testbot.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/test-bot-configmap.yaml") . | sha256sum }}
    spec:
      restartPolicy: Never
    {{- with .Values.testbot.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xrengine.testbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.testbot.podSecurityContext | nindent 8 }}
      {{- $releaseName := .Release.Name }}
      {{ if not (empty .Values.release) }}
      {{- $releaseName = .Values.release.name | default .Release.Name }}
      {{ end }}
      initContainers:
      - name: init-engine
        image: bitnami/kubectl
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -exc
          - |
            apiName="${RELEASE_NAME}-xrengine-api"
            clientName="${RELEASE_NAME}-xrengine-client"
            gamesvrName="${RELEASE_NAME}-gameserver"

            apiCount=$(kubectl get deploy $apiName -o jsonpath='{.status.availableReplicas}')
            echo "API ready count: $apiCount"

            # Wait until api count is 1.
            until [ $apiCount -ge 1 ]
            do
                sleep 5

                apiCount=$(kubectl get deploy $apiName -o jsonpath='{.status.availableReplicas}')
                echo "API ready count: $apiCount"
            done

            clientCount=$(kubectl get deploy $clientName -o jsonpath='{.status.availableReplicas}')
            echo "Client ready count: $clientCount"

            # Wait until client count is 1.
            until [ $clientCount -ge 1 ]
            do
                sleep 5

                clientCount=$(kubectl get deploy $clientName -o jsonpath='{.status.availableReplicas}')
                echo "Client ready count: $clientCount"
            done

            gamesvrCount=$(kubectl get fleet $gamesvrName -o jsonpath='{.status.readyReplicas}')
            echo "Gameserver ready count: $gamesvrCount"

            # Wait until gamesvr count is 1.
            until [ $gamesvrCount -ge 1 ]
            do
                sleep 5

                gamesvrCount=$(kubectl get fleet $gamesvrName -o jsonpath='{.status.readyReplicas}')
                echo "Gameserver ready count: $gamesvrCount"
            done

            echo "XREngine is now ready"
            exit 0
        env:
          - name: RELEASE_NAME
            value: {{ .Release.Name }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.testbot.securityContext | nindent 12 }}
          image: "{{ .Values.testbot.image.repository }}:{{ .Values.testbot.image.tag }}"
          imagePullPolicy: {{ .Values.testbot.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "xrengine.testbot.fullname" . }}
                optional: true
          env:
            - name: SERVER_MODE
              value: "client"
            - name: KUBERNETES
              value: "true"
            - name: MYSQL_USER
              value: {{ .Values.mariadb.db.user }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.db.name }}
            - name: MYSQL_PASSWORD
              {{- if not .Values.mariadb.enabled }}
              value: {{ .Values.mariadb.db.password | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.existingSecret }}
                  name: {{ .Values.mariadb.existingSecret }}
                  {{- else }}
                  name: {{ template "xrengine.mariadb.fullname" . }}
                  {{- end }}
                  key: mariadb-password
              {{- end }}
            - name: MYSQL_HOST
              value: {{ template "xrengine.mariadb.host" . }}
            - name: MYSQL_PORT
              value: {{ .Values.mariadb.externalPort | quote }}
            - name: RELEASE_NAME
              value: {{ $releaseName }}
          resources:
            {{- toYaml .Values.testbot.resources | nindent 12 }}
      {{- with .Values.testbot.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.testbot.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.testbot.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}