apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xrengine
resources:
  - xrengine.yaml
secretGenerator:
  - name: xrengine-dev-secrets
    env: xrengine-dev-secrets.env
generatorOptions:
  disableNameSuffixHash: true